//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2024. 05. 01. 16:04:28
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace CarRent.KolcsonzoModel
{
    public partial class Autok {

        public Autok()
        {
            this.Kolcsonzeseks = new List<Kolcsonzesek>();
            this.Extraks = new List<Extrak>();
            OnCreated();
        }

        public int AutoID { get; set; }

        public int MarkaID { get; set; }

        public string Modell { get; set; }

        public int Evjarat { get; set; }

        public string Valto { get; set; }

        public string Uzemanyag { get; set; }

        public int Ulesekszama { get; set; }

        public string Kivitel { get; set; }

        public int Ar { get; set; }

        public int KedvezmenyID { get; set; }

        public virtual Markak Markak { get; set; }

        public virtual Kedvezmenyek Kedvezmenyek { get; set; }

        public virtual IList<Extrak> Extraks { get; set; }

        public virtual IList<Kolcsonzesek> Kolcsonzeseks { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
