//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2024. 05. 01. 16:04:28
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace CarRent.KolcsonzoModel
{
    public partial class Kolcsonzesek {

        public Kolcsonzesek()
        {
            OnCreated();
        }

        public int FelhasznaloID { get; set; }

        public int AutoID { get; set; }

        public DateTime Mettol { get; set; }

        public DateTime Meddig { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
